<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /home/vagrant/buildkit/build/case-prospect/sites/all/modules/civicrm/ext/uk.co.compucorp.civiawards/xml/schema/CRM/CiviAwards/AwardDetail.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:71d44a4d13105ab5e970d7f996ae2883)
 */

/**
 * Database access object for the AwardDetail entity.
 */
class CRM_CiviAwards_DAO_AwardDetail extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_civiawards_award_detail';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique AwardDetails ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Case Type
   *
   * @var int
   */
  public $case_type_id;

  /**
   * One of the values of the award_type option group
   *
   * @var string
   */
  public $award_type;

  /**
   * Award Start Date
   *
   * @var date
   */
  public $start_date;

  /**
   * Award End Date
   *
   * @var date
   */
  public $end_date;

  /**
   * FK to UF Group
   *
   * @var int
   */
  public $profile_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_civiawards_award_detail';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'case_type_id', 'civicrm_case_type', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'profile_id', 'civicrm_uf_group', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_CiviAwards_ExtensionUtil::ts('Unique AwardDetails ID'),
          'required' => TRUE,
          'where' => 'civicrm_civiawards_award_detail.id',
          'table_name' => 'civicrm_civiawards_award_detail',
          'entity' => 'AwardDetail',
          'bao' => 'CRM_CiviAwards_DAO_AwardDetail',
          'localizable' => 0,
        ],
        'case_type_id' => [
          'name' => 'case_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_CiviAwards_ExtensionUtil::ts('FK to Case Type'),
          'required' => TRUE,
          'where' => 'civicrm_civiawards_award_detail.case_type_id',
          'table_name' => 'civicrm_civiawards_award_detail',
          'entity' => 'AwardDetail',
          'bao' => 'CRM_CiviAwards_DAO_AwardDetail',
          'localizable' => 0,
        ],
        'award_type' => [
          'name' => 'award_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_CiviAwards_ExtensionUtil::ts('Award Type'),
          'description' => CRM_CiviAwards_ExtensionUtil::ts('One of the values of the award_type option group'),
          'required' => TRUE,
          'maxlength' => 30,
          'size' => CRM_Utils_Type::MEDIUM,
          'where' => 'civicrm_civiawards_award_detail.award_type',
          'table_name' => 'civicrm_civiawards_award_detail',
          'entity' => 'AwardDetail',
          'bao' => 'CRM_CiviAwards_DAO_AwardDetail',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'civiawards_award_type',
            'optionEditPath' => 'civicrm/admin/options/civiawards_award_type',
          ],
        ],
        'start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => CRM_CiviAwards_ExtensionUtil::ts('Start Date'),
          'description' => CRM_CiviAwards_ExtensionUtil::ts('Award Start Date'),
          'required' => TRUE,
          'where' => 'civicrm_civiawards_award_detail.start_date',
          'table_name' => 'civicrm_civiawards_award_detail',
          'entity' => 'AwardDetail',
          'bao' => 'CRM_CiviAwards_DAO_AwardDetail',
          'localizable' => 0,
        ],
        'end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => CRM_CiviAwards_ExtensionUtil::ts('End Date'),
          'description' => CRM_CiviAwards_ExtensionUtil::ts('Award End Date'),
          'where' => 'civicrm_civiawards_award_detail.end_date',
          'table_name' => 'civicrm_civiawards_award_detail',
          'entity' => 'AwardDetail',
          'bao' => 'CRM_CiviAwards_DAO_AwardDetail',
          'localizable' => 0,
        ],
        'profile_id' => [
          'name' => 'profile_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_CiviAwards_ExtensionUtil::ts('FK to UF Group'),
          'where' => 'civicrm_civiawards_award_detail.profile_id',
          'table_name' => 'civicrm_civiawards_award_detail',
          'entity' => 'AwardDetail',
          'bao' => 'CRM_CiviAwards_DAO_AwardDetail',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'civiawards_award_detail', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'civiawards_award_detail', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
