-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_civiawards_award_panel`;
DROP TABLE IF EXISTS `civicrm_civiawards_award_manager`;
DROP TABLE IF EXISTS `civicrm_civiawards_award_detail`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_civiawards_award_detail
-- *
-- * Store Award Details
-- *
-- *******************************************************/
CREATE TABLE `civicrm_civiawards_award_detail` (
     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique AwardDetails ID',
     `case_type_id` int unsigned NOT NULL   COMMENT 'FK to Case Type',
     `award_type` varchar(30) NOT NULL   COMMENT 'One of the values of the award_type option group',
     `start_date` date NOT NULL   COMMENT 'Award Start Date',
     `end_date` date    COMMENT 'Award End Date',
     `profile_id` int unsigned    COMMENT 'FK to UF Group',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `unique_case_type`(case_type_id),
    CONSTRAINT FK_civicrm_civiawards_award_detail_case_type_id FOREIGN KEY (`case_type_id`) REFERENCES `civicrm_case_type`(`id`) ON DELETE CASCADE,
    CONSTRAINT FK_civicrm_civiawards_award_detail_profile_id FOREIGN KEY (`profile_id`) REFERENCES `civicrm_uf_group`(`id`)
);

-- /*******************************************************
-- *
-- * civicrm_civiawards_award_manager
-- *
-- * Store Award Manager Details
-- *
-- *******************************************************/
CREATE TABLE `civicrm_civiawards_award_manager` (
     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique AwardManager ID',
     `contact_id` int unsigned NOT NULL   COMMENT 'FK to Contact',
     `case_type_id` int unsigned NOT NULL   COMMENT 'FK to Case Type',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `unique_case_type_manager`(contact_id, case_type_id),
    CONSTRAINT FK_civicrm_civiawards_award_manager_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ,
    CONSTRAINT FK_civicrm_civiawards_award_manager_case_type_id FOREIGN KEY (`case_type_id`) REFERENCES `civicrm_case_type`(`id`) ON DELETE CASCADE
);

-- /*******************************************************
-- *
-- * civicrm_civiawards_award_panel
-- *
-- * Store Award Panel Details
-- *
-- *******************************************************/
CREATE TABLE `civicrm_civiawards_award_panel` (
     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique AwardReviewPanel ID',
     `title` varchar(255) NOT NULL   COMMENT 'The review panel title',
     `case_type_id` int unsigned NOT NULL   COMMENT 'FK to Case Type',
     `contact_settings` text    COMMENT 'An array of panel settings to fetch contacts belonging to this panel',
     `visibility_settings` text    COMMENT 'An array of settings related to the data access the panel contacts have to applications',
     `is_active` tinyint NOT NULL  DEFAULT 1 COMMENT 'Whether the panel is active or not',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `unique_case_type_panel_title`(title,case_type_id),
    CONSTRAINT FK_civicrm_civiawards_award_panel_case_type_id FOREIGN KEY (`case_type_id`) REFERENCES `civicrm_case_type`(`id`) ON DELETE CASCADE
);
